[package]
name = "hyper-microservice"
version = "0.1.0"
authors = ["Rutaihwa <rutaihwa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1"
hyper = "0.12"